/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "gpio.h"
#include "adc.h"
#include "TIM/tim1.h"
#include "ldr.h"

#ifdef ADC_CHANNEL_QTY
#undef ADC_CHANNEL_QTY
#define ADC_CHANNEL_QTY 1
#endif

LDR_ConfigTypeDef LDR_Config = {
    .TIM_ARR = 40000,
    .TIM_PSC = 0,
    .DMA_Channel = DMA1_Channel1,
    .ADC_Channel = ADC_CHANNEL_15,
};

int main(void)
{
    CORE_ClockInit();
    CORE_PWRInit();
    GPIO_ConfigALL();
    RTC_Init();
    GPIO_SetPin(GPIOB, GPIO_PIN8);
    GPIO_SetPin(GPIOA, GPIO_PIN12);
    SERVO_TIMConfig(TIM3, TIM_CHANNEL_2);
    SERVO_SetAngle(TIM3, TIM_CHANNEL_2, 18000);
    LDR_Init(&LDR_Config);
    LDR_Start(&LDR_Config);

    /* Loop forever */
    while (1)
    {
        CORE_EnterSTOP();
    }
}

void DMA1_Channel1_IRQHandler(void)
{
    LDR_Handler(&LDR_Config);
}
